spring:
  application:
    name: cards
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}

mq:
  queues:
    card-issuance: card-issuance
