version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: habbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=America/Sao_Paulo
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data
    command: "start-dev"
    restart: always

volumes:
  rabbitmq:
  keycloak: