version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: habbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=America/Sao_Paulo
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq: