spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      discovery:
        enabled: true
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

